var nombre;//Declaración de la variabe "nombre"
nombre="Juan";//Asignación de valor a la variable
console.log(nombre);//muestra el valor de la variable

var nombre="Maria";//Declaración de la variabe "nombre"
console.log(nombre);//muestra el valor de la variable

var nombre="Carlos";//Declaración de la variabe "nombre"
console.log(nombre);//muestra el valor de la variable

var nombre="Ana";//Declaración de la variabe "nombre"
console.log(nombre);//muestra el valor de la variable
//* Uso del la palabra reservada 'let' para declarar una variable llamada 'bebida' y asignarle diferentes valores a lo largo del código. Cada vez que se asigna un nuevo valor a la variable 'bebida', se muestra su contenido en la consola. Diferencia entre var y let: La palabra reservada 'var' tiene un alcance de función, lo que significa que la variable declarada con 'var' es accesible dentro de la función en la que se declara. Por otro lado, 'let' tiene un alcance de bloque, lo que significa que la variable declarada con 'let' solo es accesible dentro del bloque en el que se declara (por ejemplo, dentro de un bucle o una estructura condicional). Además, 'let' no permite redeclarar la misma variable dentro del mismo bloque, mientras que 'var' sí lo permite
// 
let bebida;
bebida= "Coca-Cola"
console.log(bebida);

bebida= "Fanta"
console.log(bebida);

bebida= "Sprite"
console.log(bebida);

const PI=3.14159;
console.log(PI);

