let nombre,edad,direccion,movil,correo;

nombre=prompt("Ingrese su nombre:");
edad=prompt("Ingrese su edad:");
direccion=prompt("Ingrese su direccion:");
movil=prompt("Ingrese su numero de movil:");
correo=prompt("Ingrese su correo electronico:");

console.log("Tus datos personales son:",nombre,edad,direccion,movil,correo);
console.log("Tu nombre es:",nombre);
console.log("Tu edad es:",edad);
console.log("Tu direccion es:",direccion);
console.log("Tu movil es:",movil);
console.log("Tu correo es:",correo);

document.write("Tus datos personales son:",nombre,edad,direccion,movil,correo);
document.write("<br>");
document.write("Tu nombre es:",nombre);
document.write("<br>");
document.write("Tu edad es:",edad);
document.write("<br>");
document.write("Tu direccion es:",direccion);
document.write("<br>");
document.write("Tu movil es:",movil);
document.write("<br>");
document.write("Tu correo es:",correo);